### ISSUE TITLE
Create a Navbar for the FORUM website

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#14]
Forum is a project where students of IIITA can ask their doubts or share their experiences with each other. They can join spaces or communities too.
Your Task is to create a navbar for the website.

---
Navbar should include:
- All the shortcut for different pages like profile page,community page,ask a question,answer...etc 
  (You can take the reference of Quora or Reddit)

## Guidelines
- The code should be clean and reusable.
- You have to edit in this file: [components/Navbar/index.js](https://github.com/opencodeiiita/Forum-Frontend-Web/blob/main/src/components/Navbar/index.js)
## Note
- Make sure you follow the given template before making the pull request.

**Comment by ananyaa07** [comment]
claim

**Comment by Kali-Decoder** [comment]
Claim

**Comment by yashg-116** [comment]
@ananyaa07 updates?

**Comment by ananyaa07** [comment]
@yashg-116 I'll be starting with this issue tomorrow.

**Comment by Siddhant-Agarwal4583** [comment]
claim
