### ISSUE TITLE
Design a dashboard page of the Forum website

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#24]
Forum is a project where students of IIITA can ask their doubts or share their experiences with each other. They can join spaces or communities too.
Your Task is to design a dashboard page in Figma.

---
Dashboard should include all necessary information of a user like name , profile image, question asked/solved , communities,  reward etc...
You can take reference from any other Forum website or app.

## Guidelines
- The UI should be clean.
- For submitting PR, you have to make a .txt file containing your github username and figma link and add it into the designs/homepage folder.
## Note
- The top 3 designs will be selected and will be rewarded with points.
- The final decision will be taken by mentors.
- As it is an open to all issue, therefore, no need to claim.
- Make sure you follow the given template before making the pull request.

**Comment by BINGABABA** [comment]
Claim

**Comment by Adi-R12** [comment]
its open for all issue no need to claim.. start working best 3 pr will be selected
