### ISSUE TITLE
Create the Hero section for FORUM website

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#25]
You have to create a hero section for the FORUM website. You need to replicate the below design as close as possible.

![Hero](https://user-images.githubusercontent.com/72403085/208499508-af9bbde3-97c1-4653-985b-ff93e3dbfa46.png)

 ## Resources 
[**FIGMA**](https://www.figma.com/file/1MKh89YYyiD0yTRXPgmGVA/Untitled?node-id=0%3A1&t=QH21wGpOldhtnTkd-0)

## Guidelines
- The code should be clean and reusable.
- You have to make a component for hero-section by making a folder inside [**THIS**](https://github.com/opencodeiiita/Forum-Frontend-Web/tree/main/src/components) and then create a index.js file in which you have to write your code.

## Note
- Make sure you follow the given template before making the pull request.

**Comment by RibhavBansal** [comment]
claim

**Comment by vishalola** [comment]
claim

**Comment by Finesse-734** [comment]
claim

**Comment by hargunkaur286** [comment]
claim

**Comment by yashg-116** [comment]
**Note**: You don't have to design it, rather you have to code it in react and tailwind CSS

**Comment by vishalola** [comment]
I'll code @yashg-116

**Comment by yashg-116** [comment]
> claim

Go for it

**Comment by yashg-116** [comment]
Go for it @vishalola

**Comment by yashg-116** [comment]
> I can code it
> 
> > Note: You don't have to design it, rather you have to code it in react and tailwind CSS

The issue has been assigned for now. You can claim if it will be reopened or if a new issue comes up 👍🏼

**Comment by Siddhant-Agarwal4583** [comment]
claim
