### ISSUE TITLE
Make the Hero section Responsive

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#31]
Your Task is to make the Hero Section responsive across all devices.
You can use the Forum logo from [HERE](https://www.figma.com/file/qfsOpPtPWb8qyRFvkVj7Mj/Forum-Hero-Section?node-id=0%3A1&t=5XSrfJGR383Zp8KR-0)

 ## Resources 
[**FIGMA**](https://www.figma.com/file/1MKh89YYyiD0yTRXPgmGVA/Untitled?node-id=0%3A1&t=QH21wGpOldhtnTkd-0)

## Guidelines
- The code should be clean and reusable.

## Note
- Make sure you follow the given template before making the pull request.

**Comment by Im-Madhur-Gupta** [comment]
Claim

**Comment by Im-Madhur-Gupta** [comment]
Claim

**Comment by yashg-116** [comment]
Updates @Im-Madhur-Gupta ?

**Comment by yashg-116** [comment]
> @yashg-116 I'm lagging a bit because of my intern work, will try my best to complete it by tonight.

Ok, try to complete it by tomorrow 12 noon, after that we will have to reassign this issue.

**Comment by Im-Madhur-Gupta** [comment]
Thanks man.

**Comment by Im-Madhur-Gupta** [comment]
Hey @yashg-116, I am basically rewriting the entire CSS as the person who created the Hero page had simply used `position: absolute` to position everything. I don't think I'll be able to complete this in the given time due to my other commitments, hence, I'll be unassigning myself. Apologies for the inconvenience caused.

**Comment by yashg-116** [comment]
Issue open to claim

**Comment by ananyaa07** [comment]
claim

**Comment by yashg-116** [comment]
> claim

@ananyaa07 Go for it, but make sure hero-section styling is done in CSS not using Tailwind.

**Comment by yashg-116** [comment]
Updates @ananyaa07 ?

**Comment by ananyaa07** [comment]
@yashg-116  I will complete it today
