### ISSUE TITLE
Create a SignIn page for the Forum website

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#33]
Forum is a project where students of IIITA can ask their doubts or share their experiences with each other. They can join spaces or communities too.
Your Task is to create a signIn page for the website.

---
## Note
- The theme should be attractive and try use your Creativity.
- User will login through there LDAP credentials so make form accordingly. It should require User's full name, email-id and password only.
- The signin page should have a graphics or a vector on one side and the signin form on the other side. And, since it is only an IIITA students' discussion forum, so no need to add other signin options like google, etc.

## Guidelines
- The code should be clean and reusable.
### You will have to edit in this file: [pages > signin > index.js](https://github.com/opencodeiiita/Forum-Frontend-Web/blob/main/src/pages/signin/index.js)
- Make sure you follow the given template before making the pull request.

**Comment by vishalola** [comment]
claim

**Comment by Adi-R12** [comment]
@vishalola 👍

**Comment by akshayw1** [comment]
Claim
