### ISSUE TITLE
Design a logo for project Forum

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#5]
Forum is a project where users can ask their doubts or share their experiences with each other. Design a logo based on the features of this app.

## Guidelines
- The UI should be clean.
- For submitting PR, you have to make a .txt file containing your github username and figma link and add it into the designs/logo folder.

## Note
- The top 3 designs will be selected and will be rewarded with points.
- The final decision will be taken by mentors.
- As it is an open to all issue, therefore, no need to claim.
- Make sure you follow the given template before making the pull request.

**Comment by itsme1502** [comment]
claim

**Comment by KrishayNair** [comment]
claim

**Comment by yashg-116** [comment]
It's an open to all issue. No need to claim.
Just submit your PR, we will reward the points to top 3 only.

**Comment by KrishayNair** [comment]
Ok
