### ISSUE TITLE
Create a Error Page for Forum website

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#59]
Forum is a project where students of IIITA can ask their doubts or share their experiences with each other. They can join spaces or communities too.
Your Task is to create a Error 404 page for the website.

---
## Note
- The theme should be attractive and try use your Creativity.

## Guidelines
- The code should be clean and reusable.
- You have to make an Error page in **src/pages** section.
- Make sure you follow the given template before making the pull request.

**Comment by ananyaa07** [comment]
claim

**Comment by yashg-116** [comment]
Go for it @ananyaa07

**Comment by ananyaa07** [comment]
@yashg-116 Should I use css or tailwind for styling?

**Comment by yashg-116** [comment]
> @yashg-116 Should I use css or tailwind for styling?

Tailwind is preferred

**Comment by ananyaa07** [comment]
Okay
