### ISSUE TITLE
Create HomePage of Forum website

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#64]
You have to create home page for the FORUM website. You need to replicate the below design as close as possible.

![Screenshot (316)](https://user-images.githubusercontent.com/97426655/209810642-4dcb29d8-367b-41e8-941c-5c1493bd294d.png)

 ## Resources 
[**FIGMA**](https://www.figma.com/file/JafXRsjhLbTtouheselx8G/Untitled?node-id=0%3A1&t=awBEInpkRFR07MD0-0)

## Deadline
 48 hrs
## Guidelines
- The code should be clean and reusable.
- Make sure that you make component for code reuseablity.
- you Don't need to create Navbar for this issue

## Note
- Make sure you follow the given template before making the pull request.

**Comment by ananyaa07** [comment]
claim

**Comment by GammaMicrowave** [comment]
claim

**Comment by yashg-116** [comment]
@ananyaa07 you are already assigned with 3 issues overall

**Comment by ananyaa07** [comment]
one person can be assigned with 4 issues at a time, right?

**Comment by yashg-116** [comment]
Go for it @GammaMicrowave 👍🏼

**Comment by yashg-116** [comment]
> one person can be assigned with 4 issues at a time, right?

No, max 3 only

**Comment by ananyaa07** [comment]
Okay

**Comment by ananyaa07** [comment]
@yashg-116 , In my third issue i have already created pr for tht issue, but it hasnt got merged yet in collaborative repo

**Comment by yashg-116** [comment]
> @yashg-116 , In my third issue i have already created pr for tht issue, but it hasnt got merged yet in collaborative repo

Until it is not merged, it will be counted under active issues.

**Comment by yashg-116** [comment]
Updates @GammaMicrowave

**Comment by GammaMicrowave** [comment]
Ha abhi 3-4 pm tak karke batata hu thoda busy tha
