### ISSUE TITLE
Recreate the Navbar

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#65]
Your task is to recreate the navbar of the Forum website.
Design is provided in the [**Figma link**](https://www.figma.com/file/JafXRsjhLbTtouheselx8G/Untitled?node-id=0%3A1&t=srFJEPlQ6fxxtZ76-0)

## Guidelines
- The code should be clean and reusable.
- You have to make changes inside [**THIS**](https://github.com/opencodeiiita/Forum-Frontend-Web/blob/main/src/components/Navbar/Navbar.js).

## Note
- Make sure you follow the given template before making the pull request.

**Comment by ananyaa07** [comment]
claim

**Comment by Kali-Decoder** [comment]
claim

**Comment by yashg-116** [comment]
Go for it @Kali-Decoder

**Comment by yashg-116** [comment]
Updates @Kali-Decoder ?

**Comment by Kali-Decoder** [comment]
Bhaiya tonight it is complete @yashg-116
