### ISSUE TITLE
Create the Dashboard page for FORUM website

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#69]
You have to create dashboard page for the FORUM website. You need to replicate the below design as close as possible.

![Dashboard_Forum](https://user-images.githubusercontent.com/72403085/210164422-39fc8fe8-b60e-446e-abd8-8cb32f486b01.png)

 ## Resources 
[**FIGMA**](https://www.figma.com/file/WlNyeeNQhM2BQp4v7Mqnj8/Untitled?node-id=0%3A1&t=vhe9qQ8PR5HSqvXq-0)

## Deadline
 48 hrs

## Guidelines
- There should be my answers and my communities section which should open on clicking. For now, just display **Nothing Here** on clicking them.
- Similarly, there should be separate my rewards and skillls section which should open on clicking. 
- The code should be clean and reusable.
- Make sure that you make components for code reusability.
- You don't need to create the Navbar for this issue

## Note
- Make sure you follow the given template before making the pull request.

**Comment by TheDivineAurora** [comment]
claim

**Comment by ananyaa07** [comment]
claim

**Comment by Kali-Decoder** [comment]
Claim

**Comment by yashg-116** [comment]
Go fot it @TheDivineAurora

**Comment by sushantk1274** [comment]
claim

**Comment by akshayw1** [comment]
claim

**Comment by Adi-R12** [comment]
@TheDivineAurora update
