### ISSUE TITLE
Design the layout for the home page of the Forum Webpage

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#7]
Forum is a project where students of IIITA can ask their doubts or share their experiences with each other. They can join spaces or communities too.
Your Task is to design a layout for the home page of this project in Figma.

---
Home Page should include:
- Space/button to post questions
- Feed to show already asked questions by users
- Short details of users asking questions
- Upvote and comment features on posts
- Section for showing communities/spaces joined by the user

## Guidelines
- The UI should be clean.
- For submitting PR, you have to make a .txt file containing your github username and figma link and add it into the designs/homepage folder.
## Note
- The top 3 designs will be selected and will be rewarded with points.
- The final decision will be taken by mentors.
- As it is an open to all issue, therefore, no need to claim.
- Make sure you follow the given template before making the pull request.

**Comment by TheDivineAurora** [comment]
claim

**Comment by yashg-116** [comment]
No need to claim

**Comment by TheDivineAurora** [comment]
okay
