### ISSUE TITLE
Create a Post

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#71]
You have to make a model window (page that should pop up on screen) in home page on clicking in text area of post something.
- This model window will contain three sections 1)Title 2)content(question/post) 3)tags(hashtag) and addition features like attachments.
- In last there should be a button to post your content and a cross button on top right to cancel post.
- After clicking on post button a successful message should be displayed.
- For creating model window design you can use your creativity, but should contain all features.
- Remove post button only text area will be on home page.
- You can use antd framework. for creating model window.
- Make sure you make a component for this.

![Screenshot (316)](https://user-images.githubusercontent.com/97426655/209810642-4dcb29d8-367b-41e8-941c-5c1493bd294d.png)

## Deadline
 48 hrs
## Guidelines
- The code should be clean and reusable.
- Make sure that you make component for code reusablity.
- You Don't need to create Navbar for this issue.

## Note
- Make sure you follow the given template before making the pull request.

**Comment by ananyaa07** [comment]
Claim

**Comment by yashg-116** [comment]
@ananyaa07 you have been assigned.
Make sure you have read the description for more clarity. 👍🏼

**Comment by Adi-R12** [comment]
@ananyaa07 update your work
