### ISSUE TITLE
Fix the Navbar

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#72]
Your task is to fix and improve the navbar of the Forum website.
You have to route the navbar and also make the current open page's button primary.
Search icon is also missing in the navbar search input.
Also, you have to make the navbar responsive. In mobile view, only Forum name, a search icon(on clicking it, it should expand to open a search input box) and a hamburger like icon should be there.
On clicking that icon, options like home, communities, chat, profile, signout should be shown.

## Guidelines
- The code should be clean and reusable.

## Note
- Make sure you follow the given template before making the pull request.

**Comment by Kali-Decoder** [comment]
claim

**Comment by yashg-116** [comment]
Issue open for claim

**Comment by humbleshashi8104** [comment]
Claim

**Comment by GammaMicrowave** [comment]
if no one claims i would claim it at night as i already have 3 issues

**Comment by GammaMicrowave** [comment]
Claim

**Comment by yashg-116** [comment]
Go ahead @GammaMicrowave
