### ISSUE TITLE
Implement upvote & downvote feature on post

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#73]
You have to implement a feature for upvote, downvote buttons.
- When user click any on there buttons a animation should be displayed and No of upvote and downvote should change accordingly.
- Make a component so that we can export this when required.
- Animation should be attractive.

![Screenshot (316)](https://user-images.githubusercontent.com/97426655/209810642-4dcb29d8-367b-41e8-941c-5c1493bd294d.png)

## Deadline
 48 hrs
## Guidelines
- The code should be clean and reusable.
- Make sure that you make component for code reusablity.
- You Don't need to create Navbar for this issue.

## Note
- Make sure you follow the given template before making the pull request.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Adi-R12** [comment]
@GammaMicrowave go for it

**Comment by Adi-R12** [comment]
@GammaMicrowave update your work

**Comment by GammaMicrowave** [comment]
Aaj sham tak karke discord pe dikhata hu
