### ISSUE TITLE
Add Answers and Communities sections in Dashboard page

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#77]
You have to make Answers and Community section in the Dashboard page of the Forum website.
Design is provided [HERE](https://www.figma.com/file/WlNyeeNQhM2BQp4v7Mqnj8/Untitled?node-id=0%3A1&t=HUPAGc2asdVFiaYf-0)

## Guidelines
- The code should be clean and reusable.
- Make sure that you make components for code reusability.

## Note
- Make sure you follow the given template before making the pull request.

**Comment by TheDivineAurora** [comment]
claim

**Comment by yashg-116** [comment]
Go ahead @TheDivineAurora 👍🏼

**Comment by Adi-R12** [comment]
@TheDivineAurora update

**Comment by TheDivineAurora** [comment]
Evening Tak time dedo sir 😓

**Comment by Adi-R12** [comment]
@TheDivineAurora okay..

**Comment by yashg-116** [comment]
@TheDivineAurora updates?
