### ISSUE TITLE
Create a Signup Page

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#8]
Use your creativity and make a Signup page for the Forum project.
The signup page should have a graphics or a vector on one side and the signup form on the other side. And, since it is only an IIITA students' discussion forum, so no need to add other signup options like google, etc.
It should require User's full name, email-id and password only.

You can use tailwind CSS for styling.

---
### You will have to edit in this file: [pages > signup > index.js](https://github.com/opencodeiiita/Forum-Frontend-Web/blob/main/src/pages/signup/index.js)

For using image/vector, make an assets folder inside src folder and place the required image there only, and then import that from there.

---

Make sure you follow the given template before making the pull request.

**Comment by bhumi-cka** [comment]
Claim

**Comment by hargunkaur286** [comment]
Claim

**Comment by Kali-Decoder** [comment]
Claim 💯

**Comment by Kali-Decoder** [comment]
@yashg-116  Can we use Bootstrap for css

**Comment by yashg-116** [comment]
@bhumi-cka what's the status? 
Are you still working on it?

**Comment by Adi-R12** [comment]
@Kali-Decoder yeah! you can but wait till we assign you the task..

**Comment by yashg-116** [comment]
> @yashg-116 Can we use Bootstrap for css

No, you may use tailwind for it.

**Comment by Kali-Decoder** [comment]
Task is Assigned by you or we can choose it and work on it ?? @yashg-116

**Comment by yashg-116** [comment]
It is already assigned to @bhumi-cka for now. 
You can claim it again if it will be reopened. We will assign on first come basis.

**Comment by yashg-116** [comment]
No response from @bhumi-cka , so this issue is open to claim again!

**Comment by Kali-Decoder** [comment]
Ycan i take this

**Comment by yashg-116** [comment]
Go for it @Kali-Decoder

**Comment by Kali-Decoder** [comment]
How much time i have for this ??

**Comment by yashg-116** [comment]
It will be better for you to complete it ASAP as there is an overall limit for taking only a particular number of issues at a time per user ;)
Though the normal deadline will be 48 hours from now.

**Comment by Adi-R12** [comment]
great work @Kali-Decoder 🙌
