### ISSUE TITLE
Create suggested community page

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#83]
You have to create community page for the FORUM website. You need to replicate the below design as close as possible.
![Screenshot (319)](https://user-images.githubusercontent.com/97426655/211191904-34d52114-46ff-4f3e-af52-223536f1e443.png)

#NOTE
- You will have to connect(route) with community page icon in navbar 

 ## Resources 
[**FIGMA**](https://www.figma.com/file/4A1ppgjgRBdlghaIOfoOrS/Untitled?node-id=0%3A1&t=DycRBIVGcgRN9EGd-1)

## Deadline
 48 hrs
## Guidelines
- The code should be clean and reusable.
- Make sure that you make component for code reuseablity.
- you Don't need to create Navbar for this issue

## Note
- Make sure you follow the given template before making the pull request.

**Comment by TheDivineAurora** [comment]
claim

**Comment by TheDivineAurora** [comment]
ok i have a issue going :(

**Comment by sushantk1274** [comment]
claim

**Comment by Adi-R12** [comment]
@TheDivineAurora go for it  👍

**Comment by yashg-116** [comment]
@TheDivineAurora ?
