### ISSUE TITLE
Add Feature-Create community

### ISSUE THREAD

**Issue by Adi-R12** [opencodeiiita/Forum-Frontend-Web#92]
You have to add feature - To create community page by creating a modal window on clicking the Create button in communities page.
![Screenshot (319)](https://user-images.githubusercontent.com/97426655/211191904-34d52114-46ff-4f3e-af52-223536f1e443.png)

## NOTE
- when a user clicks on create community button a modal window should pop-up with following fields:
 Name of community, description, adding profile photo and buttons to create and cancel it.

## Deadline
 48 hrs
## Guidelines
- The code should be clean and reusable.
- Make sure that you make component for code reusablity.
- you Don't need to create Navbar for this issue

## Note
- Make sure you follow the given template before making the pull request.

**Comment by GammaMicrowave** [comment]
claim

**Comment by Adi-R12** [comment]
@GammaMicrowave go ahead
