### ISSUE TITLE
Change favicon and title

### ISSUE THREAD

**Issue by yashg-116** [opencodeiiita/Forum-Frontend-Web#98]
You have to change the website title to "Forum" and also change the favicon of this website.
For favicon, you can use the logo from [HERE](https://www.figma.com/file/5RAES4waxxABkHJD5ni8Wd/Forum-Logo?node-id=0%3A1&t=gQctp7uKLnyvfQcl-0)

## Note
- Make sure you follow the given template before making the pull request.

**Comment by sushantk1274** [comment]
claim

**Comment by yashg-116** [comment]
Go ahead @sushantk1274

**Comment by yashg-116** [comment]
updates @sushantk1274 ?
